--[[
    Resource Name : JOKE_NPCTRAINING
    Developer : Joke#4873
]]--
Joke = {} or nil

Joke['npc'] = {
    zone = {
        [1] = {
            coords = vector3(-737.3802, -2029.596, 8.891602),      -- ตำแหน่ง 
            model = "mp_m_freemode_01",                            -- โมเดลเอ็นพีซี  mp_m_freemode_01 / mp_f_freemode_01
            max = 25,                                              -- ลิมิตของเอ็นพีซีได้กี่ตัว  
            respawn = 500,                                         -- ดีเลย์การเกิดของเอ็นพีซี  1000 = 1 วิ 500 = 0.5 วิ
			health = 300,                                          -- เลือดของเอ็นพีซี 
			armour  = 10000,                                       -- เกราะของเอ็นพีซี 
            dist = 20.0,                                           -- ระยะความกว้างการเกิดเอ็นพีซี
            Cloth = {
				face1 = 31,            --   หน้าตา
				skin =  34,            --   สีผิว
				hair_1 = 12,           --   ทรงผม 1
				hair_2 = 0,            --   ทรงผม 2
				hair_color_1 = 27,     --   สีผม 1
				hair_color_2 = 0,      --   สีผม 2
				tshirt_1 = 15,         --   เสื้อด้านใน
				tshirt_2 = 0,          --   สีเสื้อด้านใน
				torso_1 = 14,          --   เสื้อนอก
				torso_2 = 7,           --   สีเสื้อนอก
				decals_1 = 0,          --   สติ๊กเกอร์ 1
				decals_2 = 0,          --   สติ๊กเกอร์ 2
				arms = 75,             --   แขน/ถุงมือ
				arms_2 = 0,            --   สีถุงมือ
				pants_1 = 18,          --   กางเกง                                    
				pants_2 = 2,           --   สีกางเกง
				shoes_1 = 16,          --   รองเท้า
				shoes_2 = 0,           --   สีรองเท้า
				mask_1 = 0,            --   หน้ากาก
				mask_2 = 0,            --   สีหน้ากาก
				bproof_1 = 0,          --   เสื้อเกาะ
				bproof_2 = 0,          --   สีเสื้อเกาะ
				chain_1 = 0,           --   สร้อยคอ
				chain_2 = 0,           --   ขนหน้าอก
				helmet_1 = -1,         --   หมวก
				helmet_2 = 0,          --   สีหมวก
				watches_1 = 0,         --   นาฬิกาข้อมือ
				watches_2 = 0,         --   สีนาฬิกาข้อมือ
				ears_1 = -1,           --   อุปกรณ์เสริมหู
				ears_2 = 0,            --   สีอุปกรณ์เสริมหู
				bracelets_1 = 0,       --   กุญแจมือ 1
				bracelets_2 = 0,       --   กุญแจมือ 2
				glasses_1 = 5,         --   แว่น 1
				glasses_2 = 0,         --   แว่น 2
				bags_1 = 0,            --   กระเป๋า
				bags_2 = 0,            --   สีกระเป๋า
				eye_color = 0,         --   สีตา
				eyebrow_type = 0,      --   คิ้ว
				eyebrow_size = 0,      --   ขนาดคิ้ว
				eyebrow_color_1 = 0,   --   สีคิ้ว 1
				eyebrow_color_2 = 0,   --   สีคิ้ว 2
				makeup_type = 0,       --   เมคอัพ
				makeup_thickness = 0,  --   ความหนาเมคอัพ
				makeup_color_1 = 0,    --   สีเมคอัพ 1
				makeup_color_2 = 0,    --   สีเมคอัพ 2
				lipstick_type = 0,     --   ลิปสติก
				lipstick_thickness = 0,--   ความหนาลิปสติก
				lipstick_color_1 = 0,  --   สีลิปสติก 1
				lipstick_color_2 = 0,  --   สีลิปสติก 2
				blemishes = 0,         --   สิว
				blemishes_size= 0,     --   ความหนาของสิว
				ageing = 0,            --   ริ้วรอย
				ageing_1 =0,           --   ความหนาของริ้วรอย
				blush =0,              --   หน้าแดง
				blush_1 = 0,           --   บลัชออนหนา
				blush_color =0,        --   สีบลัช
				complexion = 0,        --   ผิว
				complexion_1 = 0,      --   ความหนาของผิว
				sun = 0,               --   หน้าหมองคล่ำ
				sun_1 = 0,             --   ความหนาหน้าหมองคล่ำ
				freckles = 0,          --   freckles
				freckles_1 = 0,        --   freckles thickness
				chest_hair = 0,        --   ขนหน้าอก
				chest_hair_1 = 0,      --   หน้าอกผมหนา
				chest_color = 0,       --   สีขน
				bodyb = 0,             --   ร่างกายเป็นสิว
				bodyb_size = 0,        --   ความหนาของร่างกายทำให้เป็นสิว
				wrinkles = 0,          --   ริ้วรอย
				wrinkle_thickness = 0, --   ความหนาของริ้วรอย
				beard_1 = 0,           --   เครา
				beard_2 = 0,           --   ขนาดเครา
				beard_3 = 0,           --   สีเครา 1
				beard_4 = 0,           --   สีเครา 2
			}
        },

		[2] = {
            coords = vector3(-1049.75, -3495.51, 14.14), -- ตำแหน่ง 
            model = "mp_m_freemode_01",                            -- โมเดลเอ็นพีซี  mp_m_freemode_01 / mp_f_freemode_01
            max = 30,                                              -- ลิมิตของเอ็นพีซีได้กี่ตัว  
            respawn = 500,                                         -- ดีเลย์การเกิด   1000 = 1 วิ
			health = 300,                                          -- เลือดของเอ็นพีซี 
			armour  = 10000,                                       -- เกราะของเอ็นพีซี 
            dist = 25.0,                                           -- ระยะความกว้างการเกิดเอ็นพีซี 
            Cloth = {
				face1 = 31,            --   หน้าตา
				skin =  34,            --   สีผิว
				hair_1 = 12,           --   ทรงผม 1
				hair_2 = 0,            --   ทรงผม 2
				hair_color_1 = 27,     --   สีผม 1
				hair_color_2 = 0,      --   สีผม 2
				tshirt_1 = 15,         --   เสื้อด้านใน
				tshirt_2 = 0,          --   สีเสื้อด้านใน
				torso_1 = 14,          --   เสื้อนอก
				torso_2 = 7,           --   สีเสื้อนอก
				decals_1 = 0,          --   สติ๊กเกอร์ 1
				decals_2 = 0,          --   สติ๊กเกอร์ 2
				arms = 75,             --   แขน/ถุงมือ
				arms_2 = 0,            --   สีถุงมือ
				pants_1 = 18,          --   กางเกง                                    
				pants_2 = 2,           --   สีกางเกง
				shoes_1 = 16,          --   รองเท้า
				shoes_2 = 0,           --   สีรองเท้า
				mask_1 = 0,            --   หน้ากาก
				mask_2 = 0,            --   สีหน้ากาก
				bproof_1 = 0,          --   เสื้อเกาะ
				bproof_2 = 0,          --   สีเสื้อเกาะ
				chain_1 = 0,           --   สร้อยคอ
				chain_2 = 0,           --   ขนหน้าอก
				helmet_1 = -1,         --   หมวก
				helmet_2 = 0,          --   สีหมวก
				watches_1 = 0,         --   นาฬิกาข้อมือ
				watches_2 = 0,         --   สีนาฬิกาข้อมือ
				ears_1 = -1,           --   อุปกรณ์เสริมหู
				ears_2 = 0,            --   สีอุปกรณ์เสริมหู
				bracelets_1 = 0,       --   กุญแจมือ 1
				bracelets_2 = 0,       --   กุญแจมือ 2
				glasses_1 = 5,         --   แว่น 1
				glasses_2 = 0,         --   แว่น 2
				bags_1 = 0,            --   กระเป๋า
				bags_2 = 0,            --   สีกระเป๋า
				eye_color = 0,         --   สีตา
				eyebrow_type = 0,      --   คิ้ว
				eyebrow_size = 0,      --   ขนาดคิ้ว
				eyebrow_color_1 = 0,   --   สีคิ้ว 1
				eyebrow_color_2 = 0,   --   สีคิ้ว 2
				makeup_type = 0,       --   เมคอัพ
				makeup_thickness = 0,  --   ความหนาเมคอัพ
				makeup_color_1 = 0,    --   สีเมคอัพ 1
				makeup_color_2 = 0,    --   สีเมคอัพ 2
				lipstick_type = 0,     --   ลิปสติก
				lipstick_thickness = 0,--   ความหนาลิปสติก
				lipstick_color_1 = 0,  --   สีลิปสติก 1
				lipstick_color_2 = 0,  --   สีลิปสติก 2
				blemishes = 0,         --   สิว
				blemishes_size= 0,     --   ความหนาของสิว
				ageing = 0,            --   ริ้วรอย
				ageing_1 =0,           --   ความหนาของริ้วรอย
				blush =0,              --   หน้าแดง
				blush_1 = 0,           --   บลัชออนหนา
				blush_color =0,        --   สีบลัช
				complexion = 0,        --   ผิว
				complexion_1 = 0,      --   ความหนาของผิว
				sun = 0,               --   หน้าหมองคล่ำ
				sun_1 = 0,             --   ความหนาหน้าหมองคล่ำ
				freckles = 0,          --   freckles
				freckles_1 = 0,        --   freckles thickness
				chest_hair = 0,        --   ขนหน้าอก
				chest_hair_1 = 0,      --   หน้าอกผมหนา
				chest_color = 0,       --   สีขน
				bodyb = 0,             --   ร่างกายเป็นสิว
				bodyb_size = 0,        --   ความหนาของร่างกายทำให้เป็นสิว
				wrinkles = 0,          --   ริ้วรอย
				wrinkle_thickness = 0, --   ความหนาของริ้วรอย
				beard_1 = 0,           --   เครา
				beard_2 = 0,           --   ขนาดเครา
				beard_3 = 0,           --   สีเครา 1
				beard_4 = 0,           --   สีเครา 2
			}
        },
		

    }
}
